### ISSUE TITLE
Tidak bisa submit file, tetapi bisa submit dari IDE

### ISSUE THREAD

**Issue by pascalalfadian** [athlonneo/SharIF-Judge#7]
Ini ada laporan dari salah satu mahasiswa, saat unggah file, seperti tidak dianggap submissionnya. Tetapi jika disubmit via text editor, bisa ditangkap.

Video bisa cek di: https://unparacid.sharepoint.com/teams/51-Dasar-dasarPemrograman/Dokumen%20Berbagi/Forms/AllItems.aspx?id=%2Fteams%2F51%2DDasar%2DdasarPemrograman%2FDokumen%20Berbagi%2FPraktikum%2FRecordings%2FDaspro%5FWeek05%5FPascal%2D20211013%5F124830%2DMeeting%20Recording%2Emp4&parent=%2Fteams%2F51%2DDasar%2DdasarPemrograman%2FDokumen%20Berbagi%2FPraktikum%2FRecordings (3 menit)

**Comment by pascalalfadian** [comment]
Credentials sudah didapat. Sedang proses penelusuran.

**Comment by athlonneo** [comment]
Di database tabel `shj_submissions`, kolom `file_name` dan `main_file_name` disimpan sebagai `varchar(30)`. Kolom `file_name` menyimpan nama file ditambah dengan `submit_id` untuk membedakan file setiap submission. Karena `submit_id` sudah mencapai ratusan (3 digit), maka pada kasus ini file disimpan sebagai `DodoDanIndeksQuateletI20004-xxx` (31 karakter) sehingga gagal masuk ke database.

Solusi untuk menyelesaikan issue ini adalah dengan menambahkan limit karakter pada kolom `file_name` dan `main_file_name`.

**Comment by pascalalfadian** [comment]
Hi @athlonneo. Baik terima kasih ya. Kalau saya simpulkan, ini berarti sebenarnya **"bug" dari Sharif-Judge sendiri ya, dan tidak terkait skripsi kamu**?

Jika ya, maka menurut saya:

1. Pull request jangan ke repository skripsi kamu, melainkan langsung ke https://github.com/ifunpar/SharIF-Judge (toh dengan perubahan kode ini, tidak akan fixed sampai di install ulang). Nanti di laporan kamu bisa tulis kontribusi ini langsung ke repo utama.
2. Limit nya mohon diganti jadi 100 saja jangan 255, supaya agak seragam dengan limit yang lain

Sementara itu, saya akan tutup kembali akses nya dan laporkan hasilnya ke William dan Pak Husnul. Kalau sudah dibuat PR nya seperti deskripsi di atas, mohon langsung close issue ini dan ~~close~~ **cancel** PR #9 ya. Trims.

Trims ya.

**Comment by athlonneo** [comment]
@pascalalfadian Benar, masalah ini berasal dari Sharif-Judge sendiri.
Pull request sudah terdapat di https://github.com/ifunpar/SharIF-Judge/pull/15.
Terima kasih.

**Comment by pascalalfadian** [comment]
Sipp.. Trims ya!
